### PR TITLE
New Launcher Icon

### PR DESCRIPTION
**Pull request by HHCHunter**
As tittle suggests.

- We now have a proper logo, so we should use it for our Icon.
- Change Windows Target Platform Version, so resources can be used correctly.
``` 
 - <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
 + <WindowsTargetPlatformVersion>10.0.17134.0</WindowsTargetPlatformVersion>
```
- Added the solution to the repo, so it's easier for people to compile outside of Appveyor etc etc.
- Changed project includes to be in English, hopefully this doesn't break anything :/

🚀

### CODE REVIEW

**Comment by HHCHunter** [comment]
Requires fixes for resource.h before merge.
Should be in draft

**Comment by HHCHunter** [comment]
Ready for review

**Review by DronCode — APPROVED** [review]
Looks nice. Approved.

**Comment by HHCHunter** [comment]
ok - finally merging this now

**Pull request merged**
